---
title: "analisis_ctas_cancer_junio_julio_emisiones_envios"
author: "Daniel Zapata"
date: "22 de agosto de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup, include=FALSE}
# Markdown options to avoid printing and set working directory
require("knitr")
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
knitr::opts_knit$set(root.dir = normalizePath("../.."))
options(prompt="Seguros> ", continue=" ") 
```


```{r}
#Inicialización del proyecto
set.seed(123)
rm(list = ls())
options(scipen=999)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(data.table,
  dplyr,
  lubridate,
  stringr,
  zoo,
  ggplot2,
  Matrix,
  stringi,
  xgboost,
  h2o,
  openxlsx)
'%!in%' <<-  Negate('%in%')
source("modelos_propension_compra_cuentas/scripts/files_tools.R")
source("modelos_propension_compra_cuentas/scripts/utils.R")
source("modelos_propension_compra_cuentas/scripts/common_reports.R")

```

```{r}
info_path <- "//bdbemcfs/Analytics/Informacion_Centralizada/Data_Analytics"
root_path <- "///bdbemcfs/Banca_Seguros_Analytics"

original_path <- os.path.join(root_path, "datos/original")
staging_path <- os.path.join(root_path, "datos/staging")
dictionary_path <- os.path.join(root_path,"datos/diccionarios")
modeling_master_path <- "datos/master/master_modeling"
scoring_master_path <- "datos/master/master_scoring"
models_path <- "propension_compra"
plots_product <- "plots/propension_compra/cuentas_ahorro"
emisions_path <- paste(original_path, "emisiones_tmk", sep = "/")
results_path <- c("resultados")
```

```{r}
#### envios 201906 ####
envio_201906 <- get_path(original_path, "cancer") %>% get_path(key_searcher = "201906") %>% fread()
names(envio_201906)
unique(envio_201906$propension)
head(envio_201906)
```


```{r}
envio_201906 <- envio_201906[, .(periodo = "201906", 
                                 definit = paste0(TIPO, IDEN), 
                                 grupo = ifelse(propension == "CON_PROPENSION", "tratamiento", "control"))]
envio_201906[, .N, by = grupo]
```

```{r}
### envios 201907 ####
envio_modelo_201907 <- get_path(original_path, "cancer") %>% get_path(key_searcher = "201907_modelo") %>% fread()

envio_all_201907 <- get_path(original_path, "cancer") %>% get_path(key_searcher = "201907_all") %>% fread()

nrow(envio_201906)
nrow(envio_all_201907)
nrow(envio_modelo_201907)*2

head(envio_modelo_201907)
head(envio_all_201907)

names(envio_all_201907)

names(envio_modelo_201907)[names(envio_modelo_201907) %!in% names(envio_all_201907)]
unique(envio_modelo_201907$CANCER_PROPEN)
unique(envio_modelo_201907$`CANCER SIN PROPEN`)
```

```{r}
envio_201907 <- envio_all_201907[, .(periodo = "201907", 
                                 definit = paste0(TIPO_ID, id_cliente))]
envio_201907[,grupo := "control"]
envio_201907[ definit %in% envio_modelo_201907[, paste0(TIPO_ID, id_cliente)], grupo := "tratamiento"]
envio_201907[, .N, by = grupo]
```

```{r}
### cargue resultados ####
resultados_201906 <- get_path(paste(original_path, "resultados_tmk", sep = "/"), "tmk_201906") %>% fread

resultados_201907 <- get_path(paste(original_path, "resultados_tmk", sep = "/"), "tmk_201907") %>% fread

resultados_201907[duplicated(`Reporte_Llamadas_EstadoBases[CCCliente]`)]
resultados_201906[duplicated(`Reporte_Llamadas_EstadoBases[CCCliente]`)]
head(resultados_201906)
unique(resultados_201906$`Reporte_Llamadas_EstadoBases[Nombre Archivo Carga]`)

dim(resultados_201906)
dim(resultados_201907)
```
 
```{r}
envio_201907[, numid := str_extract(definit, "[[:digit:]]+")]
envio_201906[, numid := str_extract(definit, "[[:digit:]]+")]
envio_201907[duplicated(numid)]
envio_201906[duplicated(numid)]

```
```{r}
envios <- rbindlist(list(envio_201906, envio_201907))
resultados_tmk <- rbindlist(list(resultados_201906[, .(periodo = "201906", numid = as.character(`Reporte_Llamadas_EstadoBases[CCCliente]`), venta = `Reporte_Llamadas_EstadoBases[VENTAS]`)], resultados_201907[, .(periodo = "201907", numid = as.character(`Reporte_Llamadas_EstadoBases[CCCliente]`), venta = `Reporte_Llamadas_EstadoBases[VENTAS]`)]))
```
```{r}
envios[, .N, by = periodo]
```
```{r}
resultados_tmk[, .N, by = periodo ]
```
```{r}
```

# data emisiones
```{r}
#### envios 201906 ####
emisiones_201906 <- get_path(original_path, "emisiones_tmk") %>% get_path(key_searcher = "201906") %>% fread()
emisiones_201907 <- get_path(original_path, "emisiones_tmk") %>% get_path(key_searcher = "201907") %>% fread()
emisiones_201906 <- emisiones_201906[CodProdSeguro == 673]
emisiones_201907 <- emisiones_201907[CodProdSeguro == 673]
unique(emisiones_201907$CodProdSeguro)
dim(emisiones_201906)
dim(emisiones_201907)
names(emisiones_201906)
head(emisiones_201906)

emisiones <- rbindlist(list(emisiones_201906[, .(periodo = substr(FechaProceso, 1, 6), numid = NumDocAsegurado)],
                           emisiones_201907[, .(periodo = substr(FechaProceso, 1, 6), numid = NumDocAsegurado)]))
emisiones[, .N, by = periodo]

```
diferencial entre envio y resultados tmk 
```{r}
envios[numid %!in% resultados_tmk$numid, .N, by = periodo]
```
diferencial entre tmk y envio
```{r}
resultados_tmk[numid %!in% envios$numid] 
```


diferencal de emisiones a ventas telemarketing: los registors que no compraron
```{r}
resultados_tmk[numid %!in% emisiones$numid, .N, by = periodo ] 
```
```{r}
resultados_tmk[venta == 1 & numid %!in% emisiones$numid, .N, by = periodo ] 
```

diferencial entre emiones y tmk
```{r}
emisiones[numid %!in% resultados_tmk$numid, .N, by = periodo ]
```
```{r}
emisiones[numid %!in% envios$numid, .N, by = periodo ]
```

```{r}
emisiones[numid %in% envios[grupo == "tratamiento", numid], modelo := 1]
emisiones[, .N , by = .(periodo, modelo)]
```



```{r}
names(emisiones_201906)
emisiones_201906[NumDocAsegurado %in% emisiones[periodo == "201906" & modelo == 1, numid], modelo := 1]
emisiones_201907[NumDocAsegurado %in% emisiones[periodo == "201907" & modelo == 1, numid], modelo := 1]
emisiones_201906 <- emisiones_201906[modelo == 1]
emisiones_201907 <- emisiones_201907[modelo == 1]
names(emisiones)
fwrite(emisiones_201906, "//bdbemcfs.bancodebogota.net/Banca_Seguros_Analytics/salidas_cosechas/emisiones_modelo_201906.csv")
fwrite(emisiones_201907, "//bdbemcfs.bancodebogota.net/Banca_Seguros_Analytics/salidas_cosechas/emisiones_modelo_201907.csv")
dim(emisiones_201906)
dim(emisiones_201907)
```

```{r}
aux <- resultados_tmk[venta == 1 & numid %!in% emisiones$numid,  ]
aux[numid %in% envios[grupo == "tratamiento", numid], modelo := 1]
aux[, .N, by = .(periodo, modelo)]

fwrite(aux, "//bdbemcfs.bancodebogota.net/Banca_Seguros_Analytics/salidas_cosechas/cedulas_sin_emision.csv")
```
```{r}
resultados_tmk[, modelo := 0]
resultados_tmk[numid %in% envios[grupo == "tratamiento", numid], modelo := 1]
resultados_tmk[, emision := 0]
resultados_tmk[numid %in% emisiones$numid, emision := 1]
resultados_tmk[, .N, by = .(periodo, modelo)]

federico <- resultados_tmk[venta != 0 | emision != 0]

resultados_tmk[, .N, by = .(periodo, modelo, venta, emision)][order(periodo,modelo, venta, emision)]
dim(resultados_tmk)
```

```{r}
fwrite(resultados_tmk, "//bdbemcfs.bancodebogota.net/Banca_Seguros_Analytics/salidas_cosechas/resultados_tmk_emision.csv")
```

```{r}
resultados_tmk[, .N, by =.(periodo, venta, modelo)]
```

```{r}
federico[, .N, by =.(periodo, venta, modelo)]
```

```{r}
federico[ modelo == 1, .N, by = periodo]
```

```{r}
federico[numid %in% federico[duplicated(numid), numid], .N, by = numid] 
```
```{r}
id_duplicados <- federico[duplicated(numid), numid]
```

